### ISSUE TITLE
Acquisitions Page Image & Copy Fields

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/JBP#1]
During the internal scrum on 8/14 when Criss was showing us the Acquisitions page he noted that in order to build out the copy on the image as shown in the screenshot below he has to create 3 separate fields:

- field for 1st number
- field for copy between numbers
- field for 2nd number

Because of the tight deadline that Criss is on he will do this later when he has more bandwidth.

![image](https://user-images.githubusercontent.com/46331985/63054962-b35cfc00-be99-11e9-995e-539d32cdb1f9.png)

Invision link for reference: https://projects.invisionapp.com/share/UFTCWB7YSNA#/screens/377770922

Thanks!

**Comment by JenStewart1** [comment]
@cmoosman1 @albertbarroso what is the immediate solve for this? It's overlapping lower than around 1600px wide

![Screen Shot 2019-08-22 at 5 21 03 PM](https://user-images.githubusercontent.com/48070399/63558338-792ad480-c501-11e9-9165-164b8effb71a.png)

**Comment by albertbarroso** [comment]
"Medium-Duty Truck Bodies" Should be Oswald - That would solve that wrapping as it is a condensed font.
"out of every" — remove text transform: uppercase - it should be lowercase and less wide

**Comment by cmoosman1** [comment]
@JenStewart1 - This is actually resolved in the current build. Lets close tickets out and not keep adding to them open a new ticket for a different issue.
