### ISSUE TITLE
Footer - privacy policy and compliance links

### ISSUE THREAD

**Issue by hringerud** [Tallwave/JBP#11]
Remove: Terms and Conditions 
Content on current site:
Privacy Policy: http://jbpoindexter.com/privacy-policy.html
Policies and Compliance: http://jbpoindexter.com/policies-and-compliance.html

**Comment by cmoosman1** [comment]
@hringerud - This should be fixed in the latest build

**Comment by JenStewart1** [comment]
@cmoosman1 I see this is in the WP admin, but not pulling on staging site

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
