### ISSUE TITLE
Company Pages - link to external sites

### ISSUE THREAD

**Issue by hringerud** [Tallwave/JBP#14]
All company pages should include a link out to their individual sites.

**See links here:** https://docs.google.com/spreadsheets/d/1k14nZUZGIsyOOgcPHjKDha9ZMGY2xVL74TQaaPNQhK4/edit?usp=sharing

All companies except TAG
In first paragraph, the company should link to the site. Example
![Screen Shot 2019-08-22 at 5 05 55 PM](https://user-images.githubusercontent.com/48070399/63557869-54cdf880-c4ff-11e9-95d0-ddbbec27da87.png)

**Comment by JenStewart1** [comment]
Updated with more information

**Comment by JenStewart1** [comment]
@cmoosman1 @hringerud I updated each page to include the sie link under the address, however, when I tried updating in the body copy - it changed the styling. Making lower priority for now.

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
