### ISSUE TITLE
Exec Bios - names at bottom of page

### ISSUE THREAD

**Issue by hringerud** [Tallwave/JBP#15]
Please update the names at the bottom of the page. I didn't see where/how to do this on WP

**Comment by KailenCampbell** [comment]
@hringerud What do the names need to be? cmoosman may already know what's being asked here but since I'm on triage duty I just want to ensure the ask is super clear.

**Comment by hringerud** [comment]
John B. Poindexter - Chairman of the Board and CEO
Marek W. May - Senior Vice President of Operations
David Nuzzo - Vice President, Chief Financial Officer and General Counsel
Norb Markert - Group VP, President and Chief Operating Officer of Morgan
Mike Ownbey - Group VP, President and Chief Operating Officer of Morgan Olson
