### ISSUE TITLE
Careers page - form header

### ISSUE THREAD

**Issue by hringerud** [Tallwave/JBP#16]
Can we change the header above the form from "How can we help you" to "Connect with our team" I didn't see where to change this in WP

**Comment by cmoosman1** [comment]
@hringerud  - This should be fixed in the latest build

**Comment by hringerud** [comment]
so close :) just remove the question mark from Connect with our team - thanks!

**Comment by cmoosman1** [comment]
@hringerud - This is resolved in the current build
