### ISSUE TITLE
Global - Dropdown (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#17]
**ISSUE**
Font styling of dropdown is incorrect. Should be:
font-family: Libre Franklin;
font-size: 16px;
font-weight: 400;
color: #303C42;
line-height: 36px;

**SCREENSHOTS**
**Designed Comp**
<img width="303" alt="dropdown_comp" src="https://user-images.githubusercontent.com/46795987/63363812-2a2a4700-c329-11e9-8632-e1bdb0cf37a3.png">

**Build**
<img width="297" alt="dropdown_build" src="https://user-images.githubusercontent.com/46795987/63363893-55ad3180-c329-11e9-8857-aa996e7a8708.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
Font has not been updated to Libre Franklin from Oswald.

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by JenStewart1** [comment]
@albertbarroso are you good?
