### ISSUE TITLE
Global - Nav (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#18]
**ISSUE**
Font styling of main nav is incorrect. Should be:
font-family: Oswald;
font-size: 14px;
font-weight: 500;
color: #0F0505;

**SCREENSHOTS**
**Designed Comp**
<img width="591" alt="nav_comp" src="https://user-images.githubusercontent.com/46795987/63364702-fa7c3e80-c32a-11e9-9bd6-828c248a20c1.png">

**Build**
<img width="508" alt="nav_build" src="https://user-images.githubusercontent.com/46795987/63364709-fe0fc580-c32a-11e9-9888-32d11a0a67e5.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
This appears corrected.
