### ISSUE TITLE
Home Page - Intro Paragraph Styling (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#19]
**ISSUE**
Font styling of intro paragraph is incorrect. Should be:
font-family: Oswald;
font-size: 22px;
font-weight: 300;
color: #0F0505;
line-height: 38px;

**SCREENSHOTS**
**Designed Comp**
<img width="325" alt="intro_comp" src="https://user-images.githubusercontent.com/46795987/63365460-880c5e00-c32c-11e9-8a7d-afecb8934080.png">

**Build**
<img width="348" alt="intro_build" src="https://user-images.githubusercontent.com/46795987/63365486-95294d00-c32c-11e9-9baf-cc215db3134c.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
This is good. (The lighter version of Oswald doesn't show up at all and I don't think there is a way around it.)
