### ISSUE TITLE
Global - Footer Text Styling (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#20]
**ISSUE**
Font styling of footer text is incorrect. Should be:

Column Titles:
font-family: Oswald;
font-size: 16px;
font-weight: 400;
color: #0F0505;

Foot Links and address:
font-family: Oswald;
font-size: 16px;
font-weight: 300;
color: #0F0505;
line-height: 21px;

**SCREENSHOTS**
**Designed Comp**
<img width="1152" alt="footer_comp" src="https://user-images.githubusercontent.com/46795987/63366049-bdfe1200-c32d-11e9-86c4-7e5ae32d9658.png">

**Build**
<img width="1143" alt="footer_build" src="https://user-images.githubusercontent.com/46795987/63366063-c6564d00-c32d-11e9-9b23-0a8fe27cc977.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
"Headquarters" Is showing Libre Franklin and should be Oswald. All others are ok.

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
Links and Address are in Libre Franklin and should be set in Oswald. Close. They are consistent now. : )
