### ISSUE TITLE
Home Page - Value Statements (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#21]
**ISSUE**
Font styling of inactive state is incorrect. Should be:

Inactive Title:
font-family: Oswald;
font-size: 24px;
font-weight: 400;
color: #AAAAAA;

Inactive Body:
font-family: Oswald;
font-size: 16px;
font-weight: 300;
color: #AAAAAA;

**SCREENSHOTS**
**Designed Comp**
<img width="1264" alt="boxes_comp" src="https://user-images.githubusercontent.com/46795987/63366678-1e418380-c32f-11e9-90c4-6649e4376b3e.png">

**Build**
<img width="1079" alt="boxes_build" src="https://user-images.githubusercontent.com/46795987/63366691-24376480-c32f-11e9-9c8d-196872e8f0bb.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
Font sizing is right. The inactive state is still #1e1e1e and not #aaaaaa.

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
This has been updated and resolved
