### ISSUE TITLE
Home Page - Logo Section (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#22]
**ISSUE**
Font styling of section is incorrect. Should be:

Section Title:
font-family: Oswald;
font-size: 48px;
font-weight: 500;
color: #0F0505;

Body:
font-family: Oswald;
font-size: 36px;
font-weight: 300;
color: #0F0505;
line-height: 32px;

**SCREENSHOTS
Designed Comp**
<img width="560" alt="work_comp" src="https://user-images.githubusercontent.com/46795987/63367199-25b55c80-c330-11e9-97f0-53ae2aeddf53.png">

**Build**
<img width="744" alt="work_build" src="https://user-images.githubusercontent.com/46795987/63367209-2cdc6a80-c330-11e9-9fb0-a4c94b0eb3a9.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
This looks good to me.
