### ISSUE TITLE
Executive Member Page - Icon missing hover (Desktop)

### ISSUE THREAD

**Issue by jenalex** [Tallwave/JBP#24]
**ISSUE**
Text should be all caps. Icon hover color should be
color: #C74A37;

**SCREENSHOTS
Designed Comp**
<img width="1102" alt="employee_comp" src="https://user-images.githubusercontent.com/46795987/63379912-2d81fa80-c34a-11e9-8c51-c1c870a2f0b0.png">

**Build**
<img width="1234" alt="employee_build" src="https://user-images.githubusercontent.com/46795987/63379928-3672cc00-c34a-11e9-9e10-510648ec7342.png">

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
The left and right arrows are missing
Position/Title text should be all caps as well as the should be set in Libre Franklin.

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
