### ISSUE TITLE
Who we are cards

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#25]
The aspect ratio for the cards should be 1:1 (square) and retain the aspect ratio on all screen sizes.

Also, I noticed that the "Morgan Corporation" card doesn't follow the same format and is smaller. Company Names (.acu-card-title) should be in Prospectus Font.

<img width="1502" alt="home_staging_who-we-are" src="https://user-images.githubusercontent.com/54121814/63553703-20067500-c4f0-11e9-8777-59b68b0f3c9b.png">

<img width="1217" alt="home_comp_who-we-are" src="https://user-images.githubusercontent.com/54121814/63553712-2a287380-c4f0-11e9-9664-6af41ca92287.png">

**Comment by cmoosman1** [comment]
This is fixed in the new build please review

**Comment by albertbarroso** [comment]
Looks good! Thanks
