### ISSUE TITLE
Page Refresh Bug

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#28]
Issue: When trying to refresh on all pages (except homepage) nothing loads

<img width="1552" alt="Screen Shot 2019-08-22 at 9 54 52 PM" src="https://user-images.githubusercontent.com/48070399/63567726-95416c80-c527-11e9-9d5d-02fed3be867e.png">

Expected Result: Page would reload on refresh

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build
