### ISSUE TITLE
Nav - Drop Down Menu (not able to close)

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#29]
Issue: Drop down menu from nav doesn't close once opened (desktop and mobile)

<img width="362" alt="Screen Shot 2019-08-22 at 10 09 50 PM" src="https://user-images.githubusercontent.com/48070399/63568307-970c2f80-c529-11e9-8df9-9b73b989ebb0.png">

Desired outcome: The drop down menu should close once opened if you click on the nav item again

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build
