### ISSUE TITLE
Our Companies Pages: Hero Image Update - Company Logo instead of Company Written Name

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/JBP#3]
During the demo with the client on 8/15 he asked for:
Add reversed out white logo to hero image, replace written company name with the logo

**Comment by JenStewart1** [comment]
@albertbarroso did you provide logos? i would consider this a P1 as it's the homepage and needs to  look good.

**Comment by albertbarroso** [comment]
All logos with the exception of TAG — I searched everywhere and no hi-res exists online:
https://drive.google.com/drive/u/0/folders/1qTwndnSyJbXfgxrfBlxWId2sx-gxL6cW

**Comment by JenStewart1** [comment]
I misunderstood this ask - let's hold until post launch
