### ISSUE TITLE
Contact Us Form - No error state

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#30]
Issue: Clicking on submit without filling out the form refreshes the homepage

Desired outcome: Should show an error message

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by JenStewart1** [comment]
I'm able to get through the form without filling it out. No error state appears. It goes straight to thank you message

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by pguevara65** [comment]
I confirmed its corrected 
http://jbpoindexterco.wpengine.com/contact-us
@JenStewart1
