### ISSUE TITLE
Acquisition Carousel - Images not scaling

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#32]
Issue: Images aren't scaling properly - they're being squished

![Screen Shot 2019-08-23 at 12 56 06 PM](https://user-images.githubusercontent.com/48070399/63620149-6538ae80-c5a5-11e9-8198-64aafef886b8.png)

Desired Outcome: Images should scale down proportionally

**Comment by JenStewart1** [comment]
cc @albertbarroso

**Comment by cmoosman1** [comment]
@JenStewart1 - This should be resolved in the current build. Images will still need to be re-sized assigned that ticket to Albert.
