### ISSUE TITLE
Executive Bios - Text too close to header image

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#34]
Issue: Name and position is too close to the image - needs more padding on desktop

![Screen Shot 2019-08-23 at 1 03 06 PM](https://user-images.githubusercontent.com/48070399/63620707-e0e72b00-c5a6-11e9-8afa-d06b5cb073df.png)

Desired Outcome: Add about 10 pixels of padding between text and image

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
