### ISSUE TITLE
Footer Changes

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#35]
Copyright line has a weird first character (didn't see where to edit in the admin). Can this left align with Privacy Policy link?

<img width="1117" alt="Screen Shot 2019-08-25 at 4 25 31 PM" src="https://user-images.githubusercontent.com/48070399/63657311-2a757880-c755-11e9-872d-9a672e498412.png">

**Comment by JenStewart1** [comment]
@albertbarroso FYI

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build.
