### ISSUE TITLE
Company Pages - Missing CTA's

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#36]
Issue: CTA's on all company pages are refreshing the page
<img width="1368" alt="Screen Shot 2019-08-25 at 4 55 18 PM" src="https://user-images.githubusercontent.com/48070399/63657656-23e90000-c759-11e9-9144-b4a588e2026e.png">

Desired Outcome: CTA's should link to the appropriate link in a new tab
See Google doc with all links
https://docs.google.com/spreadsheets/d/1k14nZUZGIsyOOgcPHjKDha9ZMGY2xVL74TQaaPNQhK4/edit?usp=sharing

**Comment by JenStewart1** [comment]
@cmoosman1 I couldn't find where to edit these in the CMS - if you show me where, I can update.

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build.
