### ISSUE TITLE
 Functionality : The Intro animation freezes up and doesn't fade blocking the user from the site

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/JBP#42]
Severity: Blocker
Location: https://jbpstage.wpengine.com/
OS / OS Version: Windows 7
Device / Browser: Internet Explorer 11
 
Expected Results: 
  When the user navigates the site, the site will keep functionality on all supported browsers
 
Actual Results: 
  When the user navigates to the site with Internet Explorer 11, the site shows the intro animation then freezes. This blocks the user from accessing the site.
 
Steps To Reproduce: 
	1. Launch https://jbpstage.wpengine.com/ on Internet Explorer 11
	2. Observe that the intro animation freezes
 
Notes: N/A

Rate of Reproduction: 100%

Attachments: 
![IE blocker](https://user-images.githubusercontent.com/10537386/63804816-3f791580-c8d5-11e9-9fcf-6206d9cfb40b.PNG)

**Comment by JenStewart1** [comment]
@cmoosman1 can you check on IE11?

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
