### ISSUE TITLE
Visual : the images on Poindexter's page are too big for mobile devices

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/JBP#48]
Severity: Major
Location: https://jbpstage.wpengine.com/john-b-poindexter
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user explores the site, all aspects of the site will scale to all supported devices.
 
Actual Results: 
  When the user navigates to Poindexter's page on any mobile device, the images are not scaled down to fit the screens
 
Steps To Reproduce: 
	1. Launch https://jbpstage.wpengine.com on Google Chrome
	2. Click About Us in the Navigation bar
	3. Click Executive Team
	4. Click John Poindexter
	5. Scroll down to the pictures
	6. Observe that the user can zoom out due to pictures outside boundary
 
Notes: N/A

Rate of Reproduction: 100%

Attachments: 
![Mobile_Image_Size_Issue](https://user-images.githubusercontent.com/10537386/63809863-9e905780-c8e0-11e9-880e-99a29d2ff7de.png)

**Comment by cmoosman1** [comment]
@albertbarroso - These images all need to be sized.

**Comment by JenStewart1** [comment]
@albertbarroso @cmoosman1 what is the status of this task?

**Comment by albertbarroso** [comment]
I resized the first 3. I'll wait until we get images from them for the rest.

**Comment by cmoosman1** [comment]
@JenStewart1 - This isnt a functional issue
