### ISSUE TITLE
Careers Page: Other Company Open Jobs

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/JBP#5]
During the demo on 8/15 the client wants to ensure that we are showing the entire company portfolio of open positions

Criss indicated that it would be possible via Word Press

Adding this issue here for tracking for Criss to show Jen/PG how this is possible via Word Press

OR if it is not create it.

Thanks!

**Comment by JenStewart1** [comment]
@cmoosman1 what does this mean?

**Comment by cmoosman1** [comment]
@JenStewart1 - This is in the latest build, any job posting can be added through the WP admin. In phase two we will address categorizing the job listings.
