### ISSUE TITLE
Visual : Text is cut off on homepage when on android devices

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/JBP#50]
Severity: Trivial
Location: https://jbpstage.wpengine.com
OS / OS Version: Global Android
Device / Browser: Global Android Mobile
 
Expected Results: 
  When the user navigates the site, the site will scale according to the supported devices.
 
Actual Results: 
  When the user navigates to the site on an android phone, some text is cut off on the homepage.
 
Steps To Reproduce: 
	1. Launch https://jbpstage.wpengine.com on Google Pixel 3
	2. Observe the text is partially cut off
 
Notes: N/A

Rate of Reproduction: 100%

Attachments: 
![Text_Cutoff](https://user-images.githubusercontent.com/10537386/63813327-7b6aa580-c8ea-11e9-92b2-7663e13ae58c.png)

**Comment by JenStewart1** [comment]
@cmoosman1 can you confirm on your android?

**Comment by cmoosman1** [comment]
Im not seeing this on my device or in the simulator.
