### ISSUE TITLE
Acquisitions Page - Carousel Imagery

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#52]
Can we add a color overlay over the imagery within the carousels to provide contrast between the image and text? The overlay was also within the comp.

https://jbpstage.wpengine.com/acquisition-strategy

**Comment by cmoosman1** [comment]
@albertbarroso  - We need these images to all be consistent in size. I have applied the CSS to handle responsive but the images are all different sizes.

**Comment by albertbarroso** [comment]
Let me know the size you'd like them at and i'll resize them. Some that were square were for square format areas (cta's) and others were at 1920x1080.

**Comment by JenStewart1** [comment]
@cmoosman1 @albertbarroso what is the status of this task?

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
