### ISSUE TITLE
Careers Page - Benefits & Perks section

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#53]
The description font should be sentence case not all uppercase:
Also, would it be possible to stick to the layout / number of columns. I'm ok with the second row only containing 2 columns.

Development —
<img width="1178" alt="Screen Shot 2019-08-29 at 12 52 50 PM" src="https://user-images.githubusercontent.com/54121814/63971812-48e0ba00-ca5c-11e9-9414-932931c67236.png">

Comp —
<img width="825" alt="Screen Shot 2019-08-29 at 12 53 58 PM" src="https://user-images.githubusercontent.com/54121814/63971839-58f89980-ca5c-11e9-887d-b6b7f1f9988d.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by JenStewart1** [comment]
@albertbarroso please confirm

**Comment by albertbarroso** [comment]
Resolved
