### ISSUE TITLE
About Us - Executive Team

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#56]
Would it be possible to have the images in the 1:1 ratio like the comp?
Also, The comp had a gradient of black from the bottom to 0 Alpha for contrast. Is that possible? If not NBD we have the overlay for text contrast already.

Current:
<img width="1581" alt="Screen Shot 2019-09-04 at 9 18 34 AM" src="https://user-images.githubusercontent.com/54121814/64274817-08b88600-cef9-11e9-86dc-a0460d2af6a3.png">

Comp:
<img width="937" alt="Screen Shot 2019-09-04 at 9 56 43 AM" src="https://user-images.githubusercontent.com/54121814/64275414-54b7fa80-cefa-11e9-816f-7fa564e56e62.png">

**Comment by cmoosman1** [comment]
@JenStewart1  - This is resolved in the current build
