### ISSUE TITLE
Home page — Learn More link 

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#57]
Within the intro text the "Learn More" link has reverted back to Helvetica. Please change to Oswald:

Current:
<img width="310" alt="Screen Shot 2019-09-04 at 8 43 48 AM" src="https://user-images.githubusercontent.com/54121814/64275707-1c64ec00-cefb-11e9-8de8-f90157c77bd3.png">

Comp:
<img width="497" alt="Screen Shot 2019-09-04 at 10 03 02 AM" src="https://user-images.githubusercontent.com/54121814/64275783-43bbb900-cefb-11e9-8009-085150aed2b6.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
