### ISSUE TITLE
Home Page — Who we Are section fonts

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#58]
The Fonts have reverted

Current:
<img width="1126" alt="Screen Shot 2019-09-04 at 8 44 35 AM" src="https://user-images.githubusercontent.com/54121814/64275954-9ac18e00-cefb-11e9-8502-cef01ebbff53.png">

Comp:
<img width="1188" alt="Screen Shot 2019-09-04 at 8 53 48 AM" src="https://user-images.githubusercontent.com/54121814/64275974-a4e38c80-cefb-11e9-9a54-a682136d6e35.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
