### ISSUE TITLE
Home Page — JB Quote section font

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#59]
The Quotation mark and the Author fonts are incorrect:

Current:
<img width="1416" alt="Screen Shot 2019-09-04 at 8 54 52 AM" src="https://user-images.githubusercontent.com/54121814/64276231-4bc82880-cefc-11e9-8ca0-2f4b7b26cdae.png">

Comp:
<img width="1431" alt="Screen Shot 2019-09-04 at 8 55 25 AM" src="https://user-images.githubusercontent.com/54121814/64276246-54b8fa00-cefc-11e9-950d-6d7b8af32e81.png">

**Comment by JenStewart1** [comment]
Closing, as we won't be launching with quotes
