### ISSUE TITLE
Our Companies — CTAs

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#60]
The descriptive text should be uppercase:

Current:
<img width="1441" alt="Screen Shot 2019-09-04 at 8 57 12 AM" src="https://user-images.githubusercontent.com/54121814/64276409-c3965300-cefc-11e9-8a0c-e7ac9c68e950.png">

Comp:
<img width="1424" alt="Screen Shot 2019-09-04 at 8 57 24 AM" src="https://user-images.githubusercontent.com/54121814/64276427-cbee8e00-cefc-11e9-98dd-05f34f9940b3.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
