### ISSUE TITLE
Mobile — What we do - Acquisition & Strategy / Corporate Development Program section

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#61]
Is it possible to zoom into the BG image in an align right position rather than repeat the BG image?

Current:
![IMG_2774](https://user-images.githubusercontent.com/54121814/64277444-330d4200-ceff-11e9-83b0-8c2b3a298508.PNG)

Comp:
![What we do_Acquisitions_mobile](https://user-images.githubusercontent.com/54121814/64277666-c21a5a00-ceff-11e9-8728-3029d0ff2a67.png)

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
