### ISSUE TITLE
Navigation Order - Company Pages

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#64]
I updated the order in the Admin, but it's not updating the on the site
![Screen Shot 2019-09-05 at 4 49 45 PM](https://user-images.githubusercontent.com/48070399/64391321-2f5fe500-cffd-11e9-9579-5c102eab8574.png)

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build

**Comment by pguevara65** [comment]
@JenStewart1 I confirmed this is completed http://jbpoindexterco.wpengine.com/contact-us
