### ISSUE TITLE
Careers — Benefits & Perks section

### ISSUE THREAD

**Issue by albertbarroso** [Tallwave/JBP#65]
Would it be possible to have the Benefits & Perks mimic the same layout as the Additional Memberships, Achievements and Awards section on the JBP bio page? Just the layout not the text styling or background visual styling. I'm ok with an asymmetrical layout.

Benefits & Perks section:
<img width="1565" alt="Screen Shot 2019-09-06 at 8 53 21 AM" src="https://user-images.githubusercontent.com/54121814/64442282-61685a00-d084-11e9-9706-8c8c99cb4882.png">

Additional Memberships, Achievements and Awards section:
<img width="1527" alt="Screen Shot 2019-09-06 at 8 53 36 AM" src="https://user-images.githubusercontent.com/54121814/64442400-92488f00-d084-11e9-8f73-4f0ba2079c7b.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
