### ISSUE TITLE
Job Posting Template Update: Add if null check

### ISSUE THREAD

**Issue by pguevara65** [Tallwave/JBP#66]

**Comment by cmoosman1** [comment]
@pguevara65 - This should be resolved in the current build

**Comment by JenStewart1** [comment]
Is the issue this?
<img width="329" alt="Screen Shot 2019-09-12 at 10 08 18 PM" src="https://user-images.githubusercontent.com/48070399/64838868-ffd74c80-d5a9-11e9-8160-d162888d7f47.png">


If so, it's not resolved

**Comment by cmoosman1** [comment]
@JenStewart1 - No this is a different issue

**Comment by pguevara65** [comment]
all set, closing this out
