### ISSUE TITLE
Masterack Page updates

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#68]
We need to remove "vehicles" after masterack. I couldn't figure out where to update in the CMS in the following places:
- Link
<img width="351" alt="Screen Shot 2019-09-12 at 9 58 33 PM" src="https://user-images.githubusercontent.com/48070399/64838541-80954900-d5a8-11e9-8001-911b184eaf4c.png">

- CTA header
<img width="734" alt="Screen Shot 2019-09-12 at 9 59 22 PM" src="https://user-images.githubusercontent.com/48070399/64838561-9b67bd80-d5a8-11e9-9940-79e7bdc4c663.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This issue is resolved
