### ISSUE TITLE
Mobile Layout - Company page

### ISSUE THREAD

**Issue by JenStewart1** [Tallwave/JBP#69]
There's a gap on the company pages between the main content and ctas

<img width="280" alt="Screen Shot 2019-09-13 at 8 41 18 AM" src="https://user-images.githubusercontent.com/48070399/64875979-02b25b80-d603-11e9-8fff-eca046271c53.png">

**Comment by cmoosman1** [comment]
@JenStewart1 - This is resolved in the current build
